In [2]:
import numpy as np

In [7]:
x = np.arange(1, 10, 0.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

## Reshaping

In [8]:
x.shape

(18,)

In [11]:
x.reshape((9, 2))

array([[1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

### 1. Create a 5x5 array of squares of numbers from 1 to 25

In [14]:
np.arange(1, 26).reshape((5, 5)) ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

## Slicing

In [17]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
a[3] = 40
a

array([  1,   2, 103,  40, 105, 106,   7,   8,   9,  10])

In [21]:
a[2:6] += 100  # modyfiying a slice of numpy's array will also modify the values in original array (unlike `list` in python)

In [22]:
a

array([  1,   2, 103, 140, 105, 106,   7,   8,   9,  10])

In [31]:
python_list = list(range(1, 11))
print(python_list)
copy = python_list[2:6]
copy[2] += 100
print(copy)
print(python_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3, 4, 105, 6]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [37]:
a = np.arange(1, 21)
b = a.reshape((5, 4))
b


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [38]:
b[1][0]

5

In [40]:
b[1:3, :2]

array([[ 5,  6],
       [ 9, 10]])

### 2. Create a 4x6 array that will have 1s on the border and 0s everywhere else

In [51]:
x = np.ones((4, 6))
x[1:-1, 1:-1] = 0
x

x = np.zeros((6,4))
x[0] = 1
x[:, 0] = 1
x


array([[1., 1., 1., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [52]:
x = np.zeros((5,5))
x[::2] = 1
x

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [60]:
x = np.arange(1, 21).reshape((5,4))
print(x)
print(x < 10)
print(x[x < 10])
x[x < 10] += 100
x

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]
 [False False False False]
 [False False False False]]
[1 2 3 4 5 6 7 8 9]


array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [64]:
x[x % 3 == 0] = 0
x

array([[101,   0, 103, 104],
       [  0, 106, 107,   0],
       [109,  10,  11,   0],
       [ 13,  14,   0,  16],
       [ 17,   0,  19,  20]])

## Random numbers

In [69]:
np.array([10, 20, 30]) + np.array([1, 2, 3])
# two arrays of the same shape can be added together (other operations work too) 

array([11, 22, 33])

In [65]:
np.random.randint(1, 10, size=(10, 10))

array([[7, 2, 8, 7, 4, 2, 4, 6, 9, 2],
       [8, 4, 1, 1, 1, 8, 8, 5, 2, 6],
       [2, 5, 6, 1, 4, 5, 2, 6, 4, 7],
       [6, 3, 7, 5, 5, 8, 1, 6, 8, 1],
       [4, 2, 2, 9, 9, 7, 6, 5, 4, 9],
       [6, 6, 3, 6, 1, 2, 5, 4, 1, 7],
       [6, 8, 9, 7, 2, 2, 5, 3, 5, 2],
       [5, 8, 4, 4, 2, 5, 5, 6, 7, 3],
       [2, 7, 9, 6, 3, 4, 2, 7, 2, 6],
       [4, 2, 4, 2, 1, 9, 9, 6, 3, 5]])

### 3. Create a 100-element array containing the results of 2-dice rolls (2d6 - roll 2 6-sided dice and add the result)

In [79]:
a = np.random.randint(1, 7, size=(10, 10))
b = np.random.randint(1, 7, size=(10, 10))
a + b

array([[ 5,  7,  9,  5,  8,  5,  9,  8,  4,  8],
       [ 5,  7,  6,  8,  5,  7, 11,  6, 12,  8],
       [ 7,  8,  6,  4,  6,  4,  9,  8,  6, 11],
       [ 7, 10,  7,  3,  9,  5,  9,  9,  7,  6],
       [ 6,  5,  3,  8,  7,  3,  8,  8,  6, 12],
       [ 4,  4,  2,  6,  9,  9,  2,  5,  7,  5],
       [ 6,  7,  4,  3,  7,  2,  5,  4,  5,  4],
       [ 6,  4,  5,  2,  9,  8,  7,  9,  5,  4],
       [ 6, 10,  6,  3,  5,  3,  7, 10,  9,  6],
       [12,  6, 11,  6, 11,  9,  8,  7,  8,  8]])

### 4. Calculate how many times each result appeared in previous task

In [80]:
np.unique(a + b, return_counts=True)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 4,  6, 10, 14, 16, 14, 14, 12,  3,  4,  3], dtype=int64))

## Broadcasting

1. Operations are possible on 2 arrays of the same shape (e.g. we can add two 3x2 arrays)
2. If the shapes are different then broadcasting mechanism checks if they are compatible:
    - if the arrays have different number of dimensions then the array with less dimensions will get more of them by prepending 1s to its shape
    - the arrays have compatible shapes if numbers on corresponding positions are the same or one of them is equal to 1.

In [ ]:
# (3, 2)
# (1, 2)

# [10, 20] - shape: (2,)
# [[10, 20]] - shape: (1, 2)
# [[10],
#  [20]] - shape: (2, 1)

    
# [[1 2]
#  [3 4]
#  [5 6]]
# +
# [[10, 10],
#  [20, 20],
#  [30, 30]]

# (3, 2) +
# (3, 1) - compatible

# (3,6,4,1,7) +
# (1,1,1,3,6) - not compatible

In [89]:
a = np.arange(1, 7).reshape((3, 2))
print(a)
b = np.arange(10, 16).reshape((3, 2))
print(b)
a + np.array([10, 20])
a + np.array([[10],
              [20],
              [30]])

[[1 2]
 [3 4]
 [5 6]]
[[10 11]
 [12 13]
 [14 15]]


array([[11, 12],
       [23, 24],
       [35, 36]])

### 5. Create a 10x10 multiplication table (for numbers 1-10) using broadcasting mechanism


In [93]:
np.arange(1, 11).reshape((10, 1)) * np.arange(1, 11)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [ ]:
# [[1,2,3],
#  [1,2,3],
#  [1,2,3]]

# *

# [[1, 1, 1],
#  [2, 2, 2],
#  [3, 3, 3]]

# =

# [[1,2,3],
#  [2,4,6],
#  [3,6,9]]